name: VanillaGenerator-API3
main: muqsit\vanillagenerator\Loader
api: 3.0.0
version: 0.0.1
authors: [Muqsit, Mineceit]
github: https://github.com/Muqsit
twitter: https://twitter.com/muqsitrayyan
forum: https://forums.pmmp.io/members/muqsit.25/

commands:
  generators:
    description: Lists the known generators
    default: op
